/*
 * Bombersauce API
 *
 * API for an agent of the Bombersauce AI-hackathon.
 *
 * OpenAPI spec version: 1.0.0
 *
 * Partly generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using IO.Swagger.Attributes;
using IO.Swagger.Models;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using System;
using static IO.Swagger.Models.ActionResponse;

namespace IO.Swagger.Controllers
{
    /// <summary>
    ///
    /// </summary>
    [ApiController]
    public class DefaultApiController : ControllerBase
    {
        /// <summary>
        ///
        /// </summary>

        /// <param name="state">Game state</param>
        /// <response code="200">The action to take</response>
        [HttpPost]
        [Route("/action")]
        [ValidateModelState]
        [SwaggerOperation("ActionPost")]
        [SwaggerResponse(statusCode: 200, type: typeof(ActionResponse), description: "The action to take")]
        public virtual IActionResult ActionPost([FromBody] ActionRequest state)
        {
            var options = Enum.GetValues<ActionEnum>();
            var action = (ActionEnum)options.GetValue(new Random().Next(options.Length));

            var result = new ActionResponse()
            {
                Action = action
            };
            
            return new ObjectResult(result);
        }

        /// <summary>
        ///
        /// </summary>

        /// <param name="body">Episode end body</param>
        /// <response code="200">Ok</response>
        [HttpPost]
        [Route("/episode_end")]
        [ValidateModelState]
        [SwaggerOperation("EpisodeEndPost")]
        public virtual IActionResult EpisodeEndPost([FromBody] EpisodeEndRequest body)
        {
            return Ok();
        }

        /// <summary>
        ///
        /// </summary>

        /// <param name="body">Initialize body</param>
        /// <response code="200">Ok</response>
        [HttpPost]
        [Route("/init_agent")]
        [ValidateModelState]
        [SwaggerOperation("InitAgentPost")]
        public virtual IActionResult InitAgentPost([FromBody] InitAgentRequest body)
        {
            return Ok();
        }

        /// <summary>
        ///
        /// </summary>

        /// <response code="200">Ok</response>
        [HttpGet]
        [Route("/ping")]
        [ValidateModelState]
        [SwaggerOperation("PingGet")]
        public virtual IActionResult PingGet()
        {
            return Ok();
        }

        /// <summary>
        ///
        /// </summary>

        /// <param name="body">Shutdown body</param>
        /// <response code="200">Ok</response>
        [HttpPost]
        [Route("/shutdown")]
        [ValidateModelState]
        [SwaggerOperation("ShutdownPost")]
        public virtual IActionResult ShutdownPost([FromBody] object body)
        {
            return Ok();
        }
    }
}